### ISSUE TITLE
Translation Language French

### ISSUE THREAD

**Issue by barto95100** [jannolii/discourse-topic-trade-buttons#9]
Hi,

how it's possible to me to change the name of button ? 

thank's for your dev :)

**Comment by jannolii** [comment]
Hi! If you know how, you may create a pull request  with French locale files (client & server). If you don't know how ... you can just forward me translated files (only right side needs to be translated). You can grab English versions form following files:

https://github.com/jannolii/discourse-topic-trade-buttons/blob/master/config/locales/client.en.yml

https://github.com/jannolii/discourse-topic-trade-buttons/blob/master/config/locales/server.en.yml

Thank you!

**Comment by barto95100** [comment]
hi, I don't know how to PR :(

how I send you the file client/server modified ?

**Comment by jannolii** [comment]
You can paste them here as code blocks ("Insert code" button)

**Comment by barto95100** [comment]
OK

Client.yml :

```
en:
  js:
    topic_trading:
      enable_sold_button: Activer le bouton 'Vendu"
      enable_purchased_button: Activer le bouton "Acheté"
      enable_exchanged_button: Activer le bouton «Échangé»
      enable_cancelled_button: Activer le bouton «Annulé»
      sold: Vendu
      purchased: Acheté
      exchanged: Échangé
      cancelled: Annulé
      error_while_marked_as_sold: Erreur lors du marquage du sujet comme "Vendu"
      error_while_marked_as_purchased: Erreur lors du marquage du sujet comme "Acheté"
      error_while_marked_as_exchanged: Erreur lors du marquage du sujet comme "Échangé"
      error_while_marked_as_cancelled: Erreur lors du marquage du sujet comme "Annulé"
      mark_as_sold_confirm: Voulez-vous vraiment que le sujet sois marquer comme "Vendu"?
      mark_as_purchased_confirm: Voulez-vous vraiment que le sujet sois marquer comme "Acheté" ?
      mark_as_exchanged_confirm: Voulez-vous vraiment que le sujet sois marquer comme "Echangé" ?
      mark_as_cancelled_confirm: Voulez-vous vraiment que le sujet sois marquer comme "Annulé" ?
```

server.yml :

```
en:
  site_settings:
    topic_trade_buttons_enabled: "Activer le bouton des ventes/achats sur les sujets ?"
  topic_trading:
    sold: Vendu
    purchased: Acheté
    exchanged: Échangé
    cancelled: Annulé 
```
